version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000" # Expõe a API na porta 3000
    env_file:
      - .env # Usar variáveis de ambiente do .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:14
    container_name: desafoga_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafoga_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
